// <auto-generated placeholder - effects appended from agent audit results>
// Data-driven effect table for stolen cards whose vanilla OnPlay reduces to
// interpreter primitives. Shape mirrors MirrorCardPowers so the interpreter
// can apply both uniformly.
#nullable enable
using System;
using System.Collections.Generic;

namespace MirrorDuelistMod;

internal enum EffectTarget
{
    Self,
    Target,
}

/// <summary>One translated effect step for a stolen card.</summary>
internal readonly struct CardEffect
{
    public readonly string Kind;
    public readonly string? Power;
    public readonly string? Status;
    public readonly string? VarKey;
    public readonly decimal Const;
    public readonly int Hits;
    public readonly EffectTarget Side;
    public readonly string? Pile;

    private CardEffect(string kind, string? power, string? status, string? varKey, decimal constValue, int hits, EffectTarget side, string? pile)
    {
        Kind = kind;
        Power = power;
        Status = status;
        VarKey = varKey;
        Const = constValue;
        Hits = hits;
        Side = side;
        Pile = pile;
    }

    public static CardEffect Damage(string? varKey, decimal constValue, int hits)
        => new("damage", null, null, varKey, constValue, hits, EffectTarget.Target, null);
    public static CardEffect Block(string? varKey, decimal constValue)
        => new("block", null, null, varKey, constValue, 1, EffectTarget.Self, null);
    public static CardEffect PowerEffect(string power, string? varKey, decimal constValue, EffectTarget side)
        => new("power", power, null, varKey, constValue, 1, side, null);
    public static CardEffect Heal(string? varKey, decimal constValue)
        => new("heal", null, null, varKey, constValue, 1, EffectTarget.Self, null);
    public static CardEffect HpLoss(string? varKey, decimal constValue)
        => new("hp_loss", null, null, varKey, constValue, 1, EffectTarget.Self, null);
    public static CardEffect DrawHand(string? varKey, decimal constValue)
        => new("draw_hand", null, null, varKey, constValue, 1, EffectTarget.Self, null);
    public static CardEffect AddStatus(string status, int n, string pile)
        => new("add_status", null, status, null, n, 1, EffectTarget.Self, pile);
    public static CardEffect Shivs(string? varKey, decimal constValue)
        => new("shivs", null, null, varKey, constValue, 1, EffectTarget.Self, null);
}

internal static class MirrorCardEffects
{
    public static IReadOnlyDictionary<string, CardEffect[]> Table => _table;

    private static readonly Dictionary<string, CardEffect[]> _table = new(StringComparer.Ordinal)
    {
        // [cardId] = new CardEffect[] { ... }  — filled from audit results
    };
}
