// <auto-generated by tools/gen_card_powers.py - do not edit by hand>
// Extracted from the vanilla card models: every PowerCmd.Apply call,
// destination-classified and audited for monster-owner safety.
#nullable enable
using System;
using System.Collections.Generic;

namespace MirrorDuelistMod;

internal enum PowerSide
{
    Self,
    Target,
}

/// <summary>One translated power application for a stolen card.</summary>
internal readonly struct CardPowerTranslation
{
    /// <summary>Kind "Model" applies the real PowerModel; "Energy"/"Draw"/
    /// "Block" feed the interpreter's pending next-turn economy instead.</summary>
    public readonly string Kind;
    public readonly string? Power;
    public readonly string? VarKey;
    public readonly PowerSide Side;

    private CardPowerTranslation(string kind, string? power, string? varKey, PowerSide side)
    {
        Kind = kind;
        Power = power;
        VarKey = varKey;
        Side = side;
    }

    public static CardPowerTranslation Model(string power, string? varKey, PowerSide side) => new("Model", power, varKey, side);
    public static CardPowerTranslation Energy(string? varKey) => new("Energy", null, varKey, PowerSide.Self);
    public static CardPowerTranslation Draw(string? varKey) => new("Draw", null, varKey, PowerSide.Self);
    public static CardPowerTranslation Block(string? varKey) => new("Block", null, varKey, PowerSide.Self);
}

internal static class MirrorCardPowers
{
    public static IReadOnlyDictionary<string, CardPowerTranslation[]> Table => _table;

    private static readonly Dictionary<string, CardPowerTranslation[]> _table = new(StringComparer.Ordinal)
    {
        ["ABRASIVE"] = new CardPowerTranslation[]
        {
        CardPowerTranslation.Model("DexterityPower", "Dexterity", PowerSide.Self),
        CardPowerTranslation.Model("ThornsPower", "ThornsPower", PowerSide.Self),
        },
        ["ACCELERANT"] = new CardPowerTranslation[]
        {
        CardPowerTranslation.Model("AccelerantPower", "Accelerant", PowerSide.Self),
        },
        ["ACCURACY"] = new CardPowerTranslation[]
        {
        CardPowerTranslation.Model("AccuracyPower", "AccuracyPower", PowerSide.Self),
        },
        ["AFTERIMAGE"] = new CardPowerTranslation[]
        {
        CardPowerTranslation.Model("AfterimagePower", "AfterimagePower", PowerSide.Self),
        },
        ["ANTICIPATE"] = new CardPowerTranslation[]
        {
        CardPowerTranslation.Model("AnticipatePower", "Dexterity", PowerSide.Self),
        },
        ["APPARITION"] = new CardPowerTranslation[]
        {
        CardPowerTranslation.Model("IntangiblePower", "IntangiblePower", PowerSide.Self),
        },
        ["ARSENAL"] = new CardPowerTranslation[]
        {
        CardPowerTranslation.Model("ArsenalPower", "ArsenalPower", PowerSide.Self),
        },
        ["ASSASSINATE"] = new CardPowerTranslation[]
        {
        CardPowerTranslation.Model("VulnerablePower", "Vulnerable", PowerSide.Target),
        },
        ["BARRICADE"] = new CardPowerTranslation[]
        {
        CardPowerTranslation.Model("BarricadePower", null, PowerSide.Self),
        },
        ["BASH"] = new CardPowerTranslation[]
        {
        CardPowerTranslation.Model("VulnerablePower", "Vulnerable", PowerSide.Target),
        },
        ["BEACONOFHOPE"] = new CardPowerTranslation[]
        {
        CardPowerTranslation.Model("BeaconOfHopePower", null, PowerSide.Self),
        },
        ["BEAMCELL"] = new CardPowerTranslation[]
        {
        CardPowerTranslation.Model("VulnerablePower", "Vulnerable", PowerSide.Target),
        },
        ["BIASEDCOGNITION"] = new CardPowerTranslation[]
        {
        CardPowerTranslation.Model("FocusPower", "FocusPower", PowerSide.Self),
        CardPowerTranslation.Model("BiasedCognitionPower", "BiasedCognitionPower", PowerSide.Self),
        },
        ["BLAZE"] = new CardPowerTranslation[]
        {
        CardPowerTranslation.Model("StrengthPower", "Strength", PowerSide.Target),
        },
        ["BLIGHTSTRIKE"] = new CardPowerTranslation[]
        {
        CardPowerTranslation.Model("DoomPower", null, PowerSide.Target),
        },
        ["BLUR"] = new CardPowerTranslation[]
        {
        CardPowerTranslation.Model("BlurPower", "Blur", PowerSide.Self),
        },
        ["BORROWEDTIME"] = new CardPowerTranslation[]
        {
        CardPowerTranslation.Model("BorrowedTimePower", "ExtraCost", PowerSide.Self),
        },
        ["BRAND"] = new CardPowerTranslation[]
        {
        CardPowerTranslation.Model("StrengthPower", "Strength", PowerSide.Self),
        },
        ["BREAK"] = new CardPowerTranslation[]
        {
        CardPowerTranslation.Model("VulnerablePower", "Vulnerable", PowerSide.Target),
        },
        ["BUBBLEBUBBLE"] = new CardPowerTranslation[]
        {
        CardPowerTranslation.Model("PoisonPower", "Poison", PowerSide.Target),
        },
        ["BUFFER"] = new CardPowerTranslation[]
        {
        CardPowerTranslation.Model("BufferPower", "BufferPower", PowerSide.Self),
        },
        ["BULKUP"] = new CardPowerTranslation[]
        {
        CardPowerTranslation.Model("StrengthPower", "Strength", PowerSide.Self),
        CardPowerTranslation.Model("DexterityPower", "Dexterity", PowerSide.Self),
        },
        ["BURST"] = new CardPowerTranslation[]
        {
        CardPowerTranslation.Model("BurstPower", "Skills", PowerSide.Self),
        },
        ["CALCIFY"] = new CardPowerTranslation[]
        {
        CardPowerTranslation.Model("CalcifyPower", "CalcifyPower", PowerSide.Self),
        },
        ["CALTROPS"] = new CardPowerTranslation[]
        {
        CardPowerTranslation.Model("ThornsPower", "ThornsPower", PowerSide.Self),
        },
        ["CHARGEBATTERY"] = new CardPowerTranslation[]
        {
        CardPowerTranslation.Energy("Energy"),
        },
        ["COLOSSUS"] = new CardPowerTranslation[]
        {
        CardPowerTranslation.Model("ColossusPower", "Colossus", PowerSide.Self),
        },
        ["COMET"] = new CardPowerTranslation[]
        {
        CardPowerTranslation.Model("WeakPower", "Weak", PowerSide.Target),
        CardPowerTranslation.Model("VulnerablePower", "Vulnerable", PowerSide.Target),
        },
        ["CONCOCT"] = new CardPowerTranslation[]
        {
        CardPowerTranslation.Model("ConcoctPower", "ConcoctPower", PowerSide.Target),
        },
        ["CONQUEROR"] = new CardPowerTranslation[]
        {
        CardPowerTranslation.Model("ConquerorPower", null, PowerSide.Target),
        },
        ["CONVERGENCE"] = new CardPowerTranslation[]
        {
        CardPowerTranslation.Energy("Energy"),
        },
        ["COORDINATE"] = new CardPowerTranslation[]
        {
        CardPowerTranslation.Model("CoordinatePower", null, PowerSide.Target),
        },
        ["CORROSIVEWAVE"] = new CardPowerTranslation[]
        {
        CardPowerTranslation.Model("CorrosiveWavePower", "CorrosiveWave", PowerSide.Self),
        },
        ["CORRUPTION"] = new CardPowerTranslation[]
        {
        CardPowerTranslation.Model("CorruptionPower", "Power", PowerSide.Self),
        },
        ["CRUELTY"] = new CardPowerTranslation[]
        {
        CardPowerTranslation.Model("CrueltyPower", "CrueltyPower", PowerSide.Self),
        },
        ["DANSEMACABRE"] = new CardPowerTranslation[]
        {
        CardPowerTranslation.Model("DanseMacabrePower", "DanseMacabrePower", PowerSide.Self),
        },
        ["DARKSHACKLES"] = new CardPowerTranslation[]
        {
        CardPowerTranslation.Model("DarkShacklesPower", "StrengthLoss", PowerSide.Target),
        },
        ["DEADLYPOISON"] = new CardPowerTranslation[]
        {
        CardPowerTranslation.Model("PoisonPower", "Poison", PowerSide.Target),
        },
        ["DEATHBRINGER"] = new CardPowerTranslation[]
        {
        CardPowerTranslation.Model("DoomPower", "Doom", PowerSide.Target),
        CardPowerTranslation.Model("WeakPower", "Weak", PowerSide.Target),
        },
        ["DEBILITATE"] = new CardPowerTranslation[]
        {
        CardPowerTranslation.Model("DebilitatePower", "DebilitatePower", PowerSide.Target),
        },
        ["DEFRAGMENT"] = new CardPowerTranslation[]
        {
        CardPowerTranslation.Model("FocusPower", "FocusPower", PowerSide.Self),
        },
        ["DEFY"] = new CardPowerTranslation[]
        {
        CardPowerTranslation.Model("WeakPower", "Weak", PowerSide.Target),
        },
        ["DELAY"] = new CardPowerTranslation[]
        {
        CardPowerTranslation.Energy("Energy"),
        },
        ["DEMONFORM"] = new CardPowerTranslation[]
        {
        CardPowerTranslation.Model("DemonFormPower", "StrengthPower", PowerSide.Self),
        },
        ["DEVOURLIFE"] = new CardPowerTranslation[]
        {
        CardPowerTranslation.Model("DevourLifePower", "DevourLifePower", PowerSide.Self),
        },
        ["DISINTEGRATION"] = new CardPowerTranslation[]
        {
        CardPowerTranslation.Model("DisintegrationPower", "DisintegrationPower", PowerSide.Self),
        },
        ["DODGEANDROLL"] = new CardPowerTranslation[]
        {
        CardPowerTranslation.Block(null),
        },
        ["DOMINATE"] = new CardPowerTranslation[]
        {
        CardPowerTranslation.Model("VulnerablePower", "VulnerablePower", PowerSide.Target),
        CardPowerTranslation.Model("StrengthPower", null, PowerSide.Self),
        },
        ["DOUBT"] = new CardPowerTranslation[]
        {
        CardPowerTranslation.Model("WeakPower", "Weak", PowerSide.Self),
        },
        ["ECHOFORM"] = new CardPowerTranslation[]
        {
        CardPowerTranslation.Model("EchoFormPower", "EchoForm", PowerSide.Self),
        },
        ["ENFEEBLINGTOUCH"] = new CardPowerTranslation[]
        {
        CardPowerTranslation.Model("EnfeeblingTouchPower", "StrengthLoss", PowerSide.Target),
        },
        ["ENVENOM"] = new CardPowerTranslation[]
        {
        CardPowerTranslation.Model("EnvenomPower", "EnvenomPower", PowerSide.Self),
        },
        ["EXPOSE"] = new CardPowerTranslation[]
        {
        CardPowerTranslation.Model("VulnerablePower", null, PowerSide.Target),
        },
        ["FADE"] = new CardPowerTranslation[]
        {
        CardPowerTranslation.Model("FadePower", "Dexterity", PowerSide.Target),
        },
        ["FALLINGSTAR"] = new CardPowerTranslation[]
        {
        CardPowerTranslation.Model("WeakPower", "Weak", PowerSide.Target),
        CardPowerTranslation.Model("VulnerablePower", "Vulnerable", PowerSide.Target),
        },
        ["FANOFKNIVES"] = new CardPowerTranslation[]
        {
        CardPowerTranslation.Model("FanOfKnivesPower", null, PowerSide.Self),
        },
        ["FASTEN"] = new CardPowerTranslation[]
        {
        CardPowerTranslation.Model("FastenPower", "ExtraBlock", PowerSide.Self),
        },
        ["FEAR"] = new CardPowerTranslation[]
        {
        CardPowerTranslation.Model("VulnerablePower", "Vulnerable", PowerSide.Target),
        },
        ["FEEDINGFRENZY"] = new CardPowerTranslation[]
        {
        CardPowerTranslation.Model("FeedingFrenzyPower", null, PowerSide.Self),
        },
        ["FEELNOPAIN"] = new CardPowerTranslation[]
        {
        CardPowerTranslation.Model("FeelNoPainPower", "Power", PowerSide.Self),
        },
        ["FIGHTME"] = new CardPowerTranslation[]
        {
        CardPowerTranslation.Model("StrengthPower", "StrengthPower", PowerSide.Self),
        CardPowerTranslation.Model("StrengthPower", "EnemyStrength", PowerSide.Target),
        },
        ["FLAMEBARRIER"] = new CardPowerTranslation[]
        {
        CardPowerTranslation.Model("FlameBarrierPower", "DamageBack", PowerSide.Self),
        },
        ["FLANKING"] = new CardPowerTranslation[]
        {
        CardPowerTranslation.Model("FlankingPower", null, PowerSide.Target),
        },
        ["FOCUSEDSTRIKE"] = new CardPowerTranslation[]
        {
        CardPowerTranslation.Model("FocusedStrikePower", "FocusPower", PowerSide.Self),
        },
        ["FOOTWORK"] = new CardPowerTranslation[]
        {
        CardPowerTranslation.Model("DexterityPower", "Dexterity", PowerSide.Self),
        },
        ["FRIENDSHIP"] = new CardPowerTranslation[]
        {
        CardPowerTranslation.Model("StrengthPower", "StrengthPower", PowerSide.Self),
        },
        ["GAMMABLAST"] = new CardPowerTranslation[]
        {
        CardPowerTranslation.Model("WeakPower", "Weak", PowerSide.Target),
        CardPowerTranslation.Model("VulnerablePower", "Vulnerable", PowerSide.Target),
        },
        ["GLITTERSTREAM"] = new CardPowerTranslation[]
        {
        CardPowerTranslation.Block(null),
        },
        ["GLOW"] = new CardPowerTranslation[]
        {
        CardPowerTranslation.Draw("Cards"),
        },
        ["GOFORTHEEYES"] = new CardPowerTranslation[]
        {
        CardPowerTranslation.Model("WeakPower", "Weak", PowerSide.Target),
        },
        ["GUIDINGSTAR"] = new CardPowerTranslation[]
        {
        CardPowerTranslation.Draw("Cards"),
        },
        ["HANG"] = new CardPowerTranslation[]
        {
        CardPowerTranslation.Model("HangPower", null, PowerSide.Target),
        },
        ["HAZE"] = new CardPowerTranslation[]
        {
        CardPowerTranslation.Model("PoisonPower", "Poison", PowerSide.Target),
        CardPowerTranslation.Model("WeakPower", "Weak", PowerSide.Target),
        },
        ["HEGEMONY"] = new CardPowerTranslation[]
        {
        CardPowerTranslation.Energy("Energy"),
        },
        ["HELLRAISER"] = new CardPowerTranslation[]
        {
        CardPowerTranslation.Model("HellraiserPower", null, PowerSide.Self),
        },
        ["HIBERNATE"] = new CardPowerTranslation[]
        {
        CardPowerTranslation.Model("HibernatePower", null, PowerSide.Self),
        },
        ["HIGHFIVE"] = new CardPowerTranslation[]
        {
        CardPowerTranslation.Model("VulnerablePower", "Vulnerable", PowerSide.Target),
        },
        ["HOTFIX"] = new CardPowerTranslation[]
        {
        CardPowerTranslation.Model("HotfixPower", "FocusPower", PowerSide.Self),
        },
        ["HYPERBEAM"] = new CardPowerTranslation[]
        {
        CardPowerTranslation.Model("HyperbeamFocusDownPower", "FocusPower", PowerSide.Self),
        },
        ["INFLAME"] = new CardPowerTranslation[]
        {
        CardPowerTranslation.Model("StrengthPower", "StrengthPower", PowerSide.Self),
        },
        ["INTERCEPT"] = new CardPowerTranslation[]
        {
        CardPowerTranslation.Model("CoveredPower", null, PowerSide.Target),
        },
        ["INVOKE"] = new CardPowerTranslation[]
        {
        CardPowerTranslation.Energy("Energy"),
        },
        ["KNOCKDOWN"] = new CardPowerTranslation[]
        {
        CardPowerTranslation.Model("KnockdownPower", "KnockdownPower", PowerSide.Target),
        },
        ["KNOWTHYPLACE"] = new CardPowerTranslation[]
        {
        CardPowerTranslation.Model("WeakPower", "Weak", PowerSide.Target),
        CardPowerTranslation.Model("VulnerablePower", "Vulnerable", PowerSide.Target),
        },
        ["LEGSWEEP"] = new CardPowerTranslation[]
        {
        CardPowerTranslation.Model("WeakPower", "Weak", PowerSide.Target),
        },
        ["MADSCIENCE"] = new CardPowerTranslation[]
        {
        CardPowerTranslation.Model("StrengthPower", "ExpertiseStrength", PowerSide.Self),
        CardPowerTranslation.Model("DexterityPower", "ExpertiseDexterity", PowerSide.Self),
        CardPowerTranslation.Model("CuriousPower", "CuriousReduction", PowerSide.Self),
        },
        ["MALAISE"] = new CardPowerTranslation[]
        {
        CardPowerTranslation.Model("StrengthPower", null, PowerSide.Target),
        CardPowerTranslation.Model("WeakPower", null, PowerSide.Target),
        },
        ["MANGLE"] = new CardPowerTranslation[]
        {
        CardPowerTranslation.Model("ManglePower", "StrengthLoss", PowerSide.Target),
        },
        ["METEORSHOWER"] = new CardPowerTranslation[]
        {
        CardPowerTranslation.Model("WeakPower", "Weak", PowerSide.Target),
        CardPowerTranslation.Model("VulnerablePower", "Vulnerable", PowerSide.Target),
        },
        ["MOLTENFIST"] = new CardPowerTranslation[]
        {
        CardPowerTranslation.Model("VulnerablePower", null, PowerSide.Target),
        },
        ["MONARCHSGAZE"] = new CardPowerTranslation[]
        {
        CardPowerTranslation.Model("MonarchsGazePower", "StrengthLoss", PowerSide.Self),
        },
        ["NEUROSURGE"] = new CardPowerTranslation[]
        {
        CardPowerTranslation.Model("NeurosurgePower", "NeurosurgePower", PowerSide.Self),
        },
        ["NEUTRALIZE"] = new CardPowerTranslation[]
        {
        CardPowerTranslation.Model("WeakPower", "Weak", PowerSide.Target),
        },
        ["NOESCAPE"] = new CardPowerTranslation[]
        {
        CardPowerTranslation.Model("DoomPower", "CalculatedDoom", PowerSide.Target),
        },
        ["NOXIOUSFUMES"] = new CardPowerTranslation[]
        {
        CardPowerTranslation.Model("NoxiousFumesPower", "PoisonPerTurn", PowerSide.Self),
        },
        ["NULL"] = new CardPowerTranslation[]
        {
        CardPowerTranslation.Model("WeakPower", "Weak", PowerSide.Target),
        },
        ["OBLIVION"] = new CardPowerTranslation[]
        {
        CardPowerTranslation.Model("OblivionPower", "Doom", PowerSide.Target),
        },
        ["ONETWOPUNCH"] = new CardPowerTranslation[]
        {
        CardPowerTranslation.Model("OneTwoPunchPower", "Attacks", PowerSide.Self),
        },
        ["OUTMANEUVER"] = new CardPowerTranslation[]
        {
        CardPowerTranslation.Energy("Energy"),
        },
        ["PANICBUTTON"] = new CardPowerTranslation[]
        {
        CardPowerTranslation.Model("NoBlockPower", "Turns", PowerSide.Self),
        },
        ["PARRY"] = new CardPowerTranslation[]
        {
        CardPowerTranslation.Model("ParryPower", "ParryPower", PowerSide.Self),
        },
        ["PATTER"] = new CardPowerTranslation[]
        {
        CardPowerTranslation.Model("VigorPower", "VigorPower", PowerSide.Self),
        },
        ["PILLAROFCREATION"] = new CardPowerTranslation[]
        {
        CardPowerTranslation.Model("PillarOfCreationPower", "Block", PowerSide.Self),
        },
        ["POISONEDSTAB"] = new CardPowerTranslation[]
        {
        CardPowerTranslation.Model("PoisonPower", "Poison", PowerSide.Target),
        },
        ["POUNCE"] = new CardPowerTranslation[]
        {
        CardPowerTranslation.Model("FreeSkillPower", null, PowerSide.Self),
        },
        ["PREDATOR"] = new CardPowerTranslation[]
        {
        CardPowerTranslation.Draw(null),
        },
        ["PREPTIME"] = new CardPowerTranslation[]
        {
        CardPowerTranslation.Model("PrepTimePower", "PrepTimePower", PowerSide.Self),
        },
        ["PROWESS"] = new CardPowerTranslation[]
        {
        CardPowerTranslation.Model("StrengthPower", "Strength", PowerSide.Self),
        CardPowerTranslation.Model("DexterityPower", "Dexterity", PowerSide.Self),
        },
        ["PUTREFY"] = new CardPowerTranslation[]
        {
        CardPowerTranslation.Model("WeakPower", null, PowerSide.Target),
        CardPowerTranslation.Model("VulnerablePower", null, PowerSide.Target),
        },
        ["REAPERFORM"] = new CardPowerTranslation[]
        {
        CardPowerTranslation.Model("ReaperFormPower", null, PowerSide.Self),
        },
        ["REBOUND"] = new CardPowerTranslation[]
        {
        CardPowerTranslation.Model("ReboundPower", null, PowerSide.Self),
        },
        ["REFINEBLADE"] = new CardPowerTranslation[]
        {
        CardPowerTranslation.Energy("Energy"),
        },
        ["REFLECT"] = new CardPowerTranslation[]
        {
        CardPowerTranslation.Model("ReflectPower", null, PowerSide.Self),
        },
        ["RELAX"] = new CardPowerTranslation[]
        {
        CardPowerTranslation.Draw("Cards"),
        CardPowerTranslation.Energy("Energy"),
        },
        ["RESONANCE"] = new CardPowerTranslation[]
        {
        CardPowerTranslation.Model("StrengthPower", null, PowerSide.Self),
        },
        ["RUPTURE"] = new CardPowerTranslation[]
        {
        CardPowerTranslation.Model("RupturePower", "Strength", PowerSide.Self),
        },
        ["SCAVENGE"] = new CardPowerTranslation[]
        {
        CardPowerTranslation.Energy("Energy"),
        },
        ["SCOURGE"] = new CardPowerTranslation[]
        {
        CardPowerTranslation.Model("DoomPower", "Doom", PowerSide.Target),
        },
        ["SEEKINGEDGE"] = new CardPowerTranslation[]
        {
        CardPowerTranslation.Model("SeekingEdgePower", null, PowerSide.Self),
        },
        ["SETUPSTRIKE"] = new CardPowerTranslation[]
        {
        CardPowerTranslation.Model("SetupStrikePower", "Strength", PowerSide.Self),
        },
        ["SHADOWMELD"] = new CardPowerTranslation[]
        {
        CardPowerTranslation.Model("ShadowmeldPower", "Power", PowerSide.Self),
        },
        ["SHADOWSTEP"] = new CardPowerTranslation[]
        {
        CardPowerTranslation.Model("ShadowStepPower", null, PowerSide.Self),
        },
        ["SHAME"] = new CardPowerTranslation[]
        {
        CardPowerTranslation.Model("FrailPower", "Frail", PowerSide.Self),
        },
        ["SHAREDFATE"] = new CardPowerTranslation[]
        {
        CardPowerTranslation.Model("StrengthPower", "PlayerStrengthLoss", PowerSide.Self),
        CardPowerTranslation.Model("StrengthPower", "EnemyStrengthLoss", PowerSide.Target),
        },
        ["SHROUD"] = new CardPowerTranslation[]
        {
        CardPowerTranslation.Model("ShroudPower", "Block", PowerSide.Self),
        },
        ["SICEM"] = new CardPowerTranslation[]
        {
        CardPowerTranslation.Model("SicEmPower", "SicEmPower", PowerSide.Target),
        },
        ["SIDESTEP"] = new CardPowerTranslation[]
        {
        CardPowerTranslation.Energy("Energy"),
        },
        ["SIGNALBOOST"] = new CardPowerTranslation[]
        {
        CardPowerTranslation.Model("SignalBoostPower", "SignalBoostPower", PowerSide.Self),
        },
        ["SLEIGHTOFFLESH"] = new CardPowerTranslation[]
        {
        CardPowerTranslation.Model("SleightOfFleshPower", "SleightOfFleshPower", PowerSide.Self),
        },
        ["SMOKESTACK"] = new CardPowerTranslation[]
        {
        CardPowerTranslation.Model("SmokestackPower", "SmokestackPower", PowerSide.Self),
        },
        ["SNAKEBITE"] = new CardPowerTranslation[]
        {
        CardPowerTranslation.Model("PoisonPower", "Poison", PowerSide.Target),
        },
        ["SNEAKY"] = new CardPowerTranslation[]
        {
        CardPowerTranslation.Model("SneakyPower", "SneakyPower", PowerSide.Self),
        },
        ["SPEEDSTER"] = new CardPowerTranslation[]
        {
        CardPowerTranslation.Model("SpeedsterPower", "SpeedsterPower", PowerSide.Self),
        },
        ["SQUASH"] = new CardPowerTranslation[]
        {
        CardPowerTranslation.Model("VulnerablePower", "Vulnerable", PowerSide.Target),
        },
        ["STRANGLE"] = new CardPowerTranslation[]
        {
        CardPowerTranslation.Model("StranglePower", "StranglePower", PowerSide.Target),
        },
        ["SUCKERPUNCH"] = new CardPowerTranslation[]
        {
        CardPowerTranslation.Model("WeakPower", "Weak", PowerSide.Target),
        },
        ["SUPPRESS"] = new CardPowerTranslation[]
        {
        CardPowerTranslation.Model("WeakPower", "Weak", PowerSide.Target),
        },
        ["SYNCHRONIZE"] = new CardPowerTranslation[]
        {
        CardPowerTranslation.Model("SynchronizePower", "CalculatedFocus", PowerSide.Self),
        },
        ["SYNTHESIS"] = new CardPowerTranslation[]
        {
        CardPowerTranslation.Model("FreePowerPower", null, PowerSide.Self),
        },
        ["TANK"] = new CardPowerTranslation[]
        {
        CardPowerTranslation.Model("TankPower", null, PowerSide.Self),
        },
        ["TAUNT"] = new CardPowerTranslation[]
        {
        CardPowerTranslation.Model("VulnerablePower", "Vulnerable", PowerSide.Target),
        },
        ["TERRAFORMING"] = new CardPowerTranslation[]
        {
        CardPowerTranslation.Model("VigorPower", "VigorPower", PowerSide.Self),
        },
        ["THEBOMB"] = new CardPowerTranslation[]
        {
        CardPowerTranslation.Model("TheBombPower", "Turns", PowerSide.Self),
        },
        ["THEGAMBIT"] = new CardPowerTranslation[]
        {
        CardPowerTranslation.Model("TheGambitPower", null, PowerSide.Self),
        },
        ["THEHUNT"] = new CardPowerTranslation[]
        {
        CardPowerTranslation.Model("TheHuntPower", null, PowerSide.Self),
        },
        ["THUNDERCLAP"] = new CardPowerTranslation[]
        {
        CardPowerTranslation.Model("VulnerablePower", "Vulnerable", PowerSide.Target),
        },
        ["TORICTOUGHNESS"] = new CardPowerTranslation[]
        {
        CardPowerTranslation.Model("ToricToughnessPower", "Turns", PowerSide.Self),
        },
        ["TRACKING"] = new CardPowerTranslation[]
        {
        CardPowerTranslation.Model("TrackingPower", null, PowerSide.Self),
        },
        ["TREMBLE"] = new CardPowerTranslation[]
        {
        CardPowerTranslation.Model("VulnerablePower", "Vulnerable", PowerSide.Target),
        },
        ["UNMOVABLE"] = new CardPowerTranslation[]
        {
        CardPowerTranslation.Model("UnmovablePower", null, PowerSide.Self),
        },
        ["UNRELENTING"] = new CardPowerTranslation[]
        {
        CardPowerTranslation.Model("FreeAttackPower", null, PowerSide.Self),
        },
        ["UPPERCUT"] = new CardPowerTranslation[]
        {
        CardPowerTranslation.Model("WeakPower", null, PowerSide.Target),
        CardPowerTranslation.Model("VulnerablePower", null, PowerSide.Target),
        },
        ["VEILPIERCER"] = new CardPowerTranslation[]
        {
        CardPowerTranslation.Model("VeilpiercerPower", null, PowerSide.Self),
        },
        ["VOIDFORM"] = new CardPowerTranslation[]
        {
        CardPowerTranslation.Model("VoidFormPower", "VoidFormPower", PowerSide.Self),
        },
        ["WRAITHFORM"] = new CardPowerTranslation[]
        {
        CardPowerTranslation.Model("IntangiblePower", "IntangiblePower", PowerSide.Self),
        CardPowerTranslation.Model("WraithFormPower", "WraithFormPower", PowerSide.Self),
        },
    };
}
