// <auto-generated placeholder - effects appended from agent audit results>
// Data-driven effect table for stolen cards whose vanilla OnPlay reduces to
// interpreter primitives. Shape mirrors MirrorCardPowers so the interpreter
// can apply both uniformly.
#nullable enable
using System;
using System.Collections.Generic;

namespace MirrorDuelistMod;

internal enum EffectTarget
{
    Self,
    Target,
}

/// <summary>One translated effect step for a stolen card.</summary>
internal readonly struct CardEffect
{
    public readonly string Kind;
    public readonly string? Power;
    public readonly string? Status;
    public readonly string? VarKey;
    public readonly decimal Const;
    public readonly int Hits;
    public readonly EffectTarget Side;
    public readonly string? Pile;

    private CardEffect(string kind, string? power, string? status, string? varKey, decimal constValue, int hits, EffectTarget side, string? pile)
    {
        Kind = kind;
        Power = power;
        Status = status;
        VarKey = varKey;
        Const = constValue;
        Hits = hits;
        Side = side;
        Pile = pile;
    }

    public static CardEffect Damage(string? varKey, decimal constValue, int hits)
        => new("damage", null, null, varKey, constValue, hits, EffectTarget.Target, null);
    public static CardEffect Block(string? varKey, decimal constValue)
        => new("block", null, null, varKey, constValue, 1, EffectTarget.Self, null);
    public static CardEffect PowerEffect(string power, string? varKey, decimal constValue, EffectTarget side)
        => new("power", power, null, varKey, constValue, 1, side, null);
    public static CardEffect Heal(string? varKey, decimal constValue)
        => new("heal", null, null, varKey, constValue, 1, EffectTarget.Self, null);
    public static CardEffect HpLoss(string? varKey, decimal constValue)
        => new("hp_loss", null, null, varKey, constValue, 1, EffectTarget.Self, null);
    public static CardEffect DrawHand(string? varKey, decimal constValue)
        => new("draw_hand", null, null, varKey, constValue, 1, EffectTarget.Self, null);
    public static CardEffect AddStatus(string status, int n, string pile)
        => new("add_status", null, status, null, n, 1, EffectTarget.Self, pile);
    public static CardEffect Shivs(string? varKey, decimal constValue)
        => new("shivs", null, null, varKey, constValue, 1, EffectTarget.Self, null);
    public static CardEffect EnergyNow(string? varKey, decimal constValue)
        => new("energy_now", null, null, varKey, constValue, 1, EffectTarget.Self, null);
    public static CardEffect SummonOsty(string? varKey, decimal constValue)
        => new("summon_osty", null, null, varKey, constValue, 1, EffectTarget.Self, null);
    public static CardEffect Forge(string? varKey, decimal constValue)
        => new("forge", null, null, varKey, constValue, 1, EffectTarget.Self, null);
    public static CardEffect MaxHpLoss(string? varKey, decimal constValue)
        => new("max_hp_loss", null, null, varKey, constValue, 1, EffectTarget.Self, null);
}

internal static class MirrorCardEffects
{
    public static IReadOnlyDictionary<string, CardEffect[]> Table => _table;

    private static readonly Dictionary<string, CardEffect[]> _table = new(StringComparer.Ordinal)
    {
        // ---- energy skills (interpreter continuation energy) ----
        ["ADRENALINE"] = new[] { CardEffect.EnergyNow("Energy", 2), CardEffect.DrawHand("Cards", 1) },
        ["ALIGNMENT"] = new[] { CardEffect.EnergyNow("Energy", 2) },
        ["BLOODLETTING"] = new[] { CardEffect.HpLoss("HpLoss", 3), CardEffect.EnergyNow("Energy", 2) },
        ["BRIGHTFLAME"] = new[] { CardEffect.EnergyNow("Energy", 3), CardEffect.DrawHand("Cards", 1), CardEffect.MaxHpLoss("MaxHp", 6) },
        ["FORGOTTENRITUAL"] = new[] { CardEffect.EnergyNow("Energy", 2) },
        ["FUEL"] = new[] { CardEffect.EnergyNow("Energy", 2) },
        ["LUMINESCE"] = new[] { CardEffect.EnergyNow("Energy", 2) },
        ["OFFERING"] = new[] { CardEffect.HpLoss("HpLoss", 6), CardEffect.EnergyNow("Energy", 2), CardEffect.DrawHand("Cards", 5) },
        ["PRODUCTION"] = new[] { CardEffect.EnergyNow("Energy", 2) },
        ["RESTLESSNESS"] = new[] { CardEffect.DrawHand("Cards", 1), CardEffect.EnergyNow("Energy", 1) },
        ["SUPERCRITICAL"] = new[] { CardEffect.EnergyNow("Energy", 2) },
        ["TACTICIAN"] = new[] { CardEffect.EnergyNow("Energy", 1) },
        ["WISP"] = new[] { CardEffect.EnergyNow("Energy", 1) },
        // ---- draw skills ----
        ["DRUMOFBATTLE"] = new[] { CardEffect.DrawHand("Cards", 2) },
        ["EXPERTISE"] = new[] { CardEffect.DrawHand("Cards", 3) },
        ["HUDDLEUP"] = new[] { CardEffect.DrawHand("Cards", 2) },
        ["IMPATIENCE"] = new[] { CardEffect.DrawHand("Cards", 2) },
        ["MASTEROFTHESTRATEGY"] = new[] { CardEffect.DrawHand("Cards", 3) },
        ["PARSE"] = new[] { CardEffect.DrawHand("Cards", 2) },
        ["PROPHESIZE"] = new[] { CardEffect.DrawHand("Cards", 2) },
        ["REFLEX"] = new[] { CardEffect.DrawHand("Cards", 2) },
        ["SCRAWL"] = new[] { CardEffect.DrawHand("Cards", 1) },
        ["SKIM"] = new[] { CardEffect.DrawHand("Cards", 2) },
        ["SOUL"] = new[] { CardEffect.DrawHand("Cards", 2) },
        ["COOLHEADED"] = new[] { CardEffect.DrawHand("Cards", 1) },
        // ---- summon the mirror Osty ----
        ["AFTERLIFE"] = new[] { CardEffect.SummonOsty("Summon", 1) },
        ["BODYGUARD"] = new[] { CardEffect.SummonOsty("Summon", 1) },
        ["DIRGE"] = new[] { CardEffect.SummonOsty("Summon", 1) },
        ["LEGIONOFBONE"] = new[] { CardEffect.SummonOsty("Summon", 1) },
        ["REANIMATE"] = new[] { CardEffect.SummonOsty("Summon", 1) },
        // ---- forge (Necrobinder forge, mirror-player-safe try/catch) ----
        ["THESMITH"] = new[] { CardEffect.Forge("Forge", 1) },
        ["SPOILSOFBATTLE"] = new[] { CardEffect.Forge("Forge", 1), CardEffect.DrawHand("Cards", 1) },
        ["BIGBANG"] = new[] { CardEffect.DrawHand("Cards", 1), CardEffect.EnergyNow("Energy", 1), CardEffect.Forge("Forge", 1) },
    };
}
