// <auto-generated by tools/gen_hit_counts.py - do not edit by hand>
#nullable enable
using System;
using System.Collections.Generic;

namespace MirrorDuelistMod;

/// <summary>Constant hit counts (WithHitCount) extracted from each
/// card's OnPlay. Dynamic counts use Repeat/CalculatedHits vars and are
/// read at runtime instead.</summary>
internal static class MirrorHitCounts
{
    public static bool TryGet(string cardId, out int hits)
    {
        return _hits.TryGetValue(cardId, out hits);
    }

    private static readonly Dictionary<string, int> _hits = new(StringComparer.Ordinal)
    {
        ["ASTRALPULSE"] = 2,
        ["DAGGERSPRAY"] = 2,
        ["MAUL"] = 2,
        ["REFRACT"] = 2,
        ["RIPANDTEAR"] = 2,
        ["THRASH"] = 2,
        ["TWINSTRIKE"] = 2,
        ["UPROAR"] = 2,
    };
}
