"""Generate MirrorHitCounts.cs: per-card constant hit counts from OnPlay.

Multi-hit cards express their hit count as `.WithHitCount(N)` on the attack
builder (dynamic counts use the Repeat/CalculatedHits vars, which the
interpreter reads at runtime). Extract every constant WithHitCount per card.
"""
from __future__ import annotations

import re
from pathlib import Path

CARDS = Path("D:/L/Study/modbulid/src/Core/Models/Cards")
OUT = Path("D:/L/Study/mod/MirrorDuelist/MirrorHitCounts.cs")

ONPLAY_RE = re.compile(r"protected override (?:async )?Task OnPlay\(PlayerChoiceContext choiceContext, CardPlay cardPlay\)\s*\{")
HITCOUNT_RE = re.compile(r"\.WithHitCount\((\d+)\)")


def body_after(text: str, start: int) -> str:
    depth = 0
    i = start
    while i < len(text):
        if text[i] == "{":
            depth += 1
        elif text[i] == "}":
            depth -= 1
            if depth == 0:
                return text[start + 1:i]
        i += 1
    return text[start:]


def normalize(name: str) -> str:
    return re.sub(r"[^A-Za-z0-9]", "", name).upper()


def main() -> None:
    entries: list[str] = []
    for path in sorted(CARDS.glob("*.cs")):
        text = path.read_text(encoding="utf-8")
        if "WithHitCount" not in text:
            continue
        op = ONPLAY_RE.search(text)
        if not op:
            continue
        body = body_after(text, op.end() - 1)
        found = {int(n) for n in HITCOUNT_RE.findall(body)}
        if found:
            hits = max(found)
            entries.append(f'        ["{normalize(path.stem)}"] = {hits},')

    lines = [
        "// <auto-generated by tools/gen_hit_counts.py - do not edit by hand>",
        "#nullable enable",
        "using System;",
        "using System.Collections.Generic;",
        "",
        "namespace MirrorDuelistMod;",
        "",
        "/// <summary>Constant hit counts (WithHitCount) extracted from each",
        "/// card's OnPlay. Dynamic counts use Repeat/CalculatedHits vars and are",
        "/// read at runtime instead.</summary>",
        "internal static class MirrorHitCounts",
        "{",
        "    public static bool TryGet(string cardId, out int hits)",
        "    {",
        "        return _hits.TryGetValue(cardId, out hits);",
        "    }",
        "",
        "    private static readonly Dictionary<string, int> _hits = new(StringComparer.Ordinal)",
        "    {",
        *entries,
        "    };",
        "}",
    ]
    OUT.write_text("\n".join(lines) + "\n", encoding="utf-8")
    print(f"hit-count entries: {len(entries)}")


if __name__ == "__main__":
    main()
